---
- src: aeimer.install_bat
  version: v1.1
  name: bat
- src: fubarhouse.golang
  version: 2.9.0
  name: golang
- src: gantsign.intellij
  version: 5.10.0
  name: intellij
- src: https://github.com/morgangraphics/ansible-role-nvm
  version: master
  name: node
- src: geerlingguy.pip
  version: 1.3.0
  name: pip
- src: Comcast.sdkman
  version: 1.6.2
  name: sdkman
- src: viasite-ansible.zsh
  version: v3.2.6
  name: zsh